export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const CHATBOT_REQUEST = 'CHATBOT_REQUEST';
export const CHATBOT_SUCCESS = 'CHATBOT_SUCCESS';
export const CHATBOT_FAILURE = 'CHATBOT_FAILURE';
